---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - petstore.example.com
  resources:
  - orders
  - petfindbystatusquerys
  - petfindbytagsquerys
  - pets
  - petstoreaggregates
  - petstorebundles
  - petuploadimageactions
  - storeinventoryquerys
  - usercreatewithlistactions
  - userloginquerys
  - userlogoutquerys
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - petstore.example.com
  resources:
  - orders/finalizers
  - pets/finalizers
  - petstoreaggregates/finalizers
  - petstorebundles/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - petstore.example.com
  resources:
  - orders/status
  - petfindbystatusquerys/status
  - petfindbytagsquerys/status
  - pets/status
  - petstoreaggregates/status
  - petstorebundles/status
  - petuploadimageactions/status
  - storeinventoryquerys/status
  - usercreatewithlistactions/status
  - userloginquerys/status
  - userlogoutquerys/status
  - users/status
  verbs:
  - get
  - patch
  - update
