---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - petstore.example.com
  resources:
  - orders
  - petfindbystatusqueries
  - petfindbytagsqueries
  - pets
  - petstoreaggregates
  - petstorebundles
  - petuploadimageactions
  - storeinventoryqueries
  - usercreatewithlistactions
  - userloginqueries
  - userlogoutqueries
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - petstore.example.com
  resources:
  - orders/finalizers
  - pets/finalizers
  - petstoreaggregates/finalizers
  - petstorebundles/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - petstore.example.com
  resources:
  - orders/status
  - petfindbystatusqueries/status
  - petfindbytagsqueries/status
  - pets/status
  - petstoreaggregates/status
  - petstorebundles/status
  - petuploadimageactions/status
  - storeinventoryqueries/status
  - usercreatewithlistactions/status
  - userloginqueries/status
  - userlogoutqueries/status
  - users/status
  verbs:
  - get
  - patch
  - update
