apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: petstore-system
  labels:
    app.kubernetes.io/name: petstore
    app.kubernetes.io/managed-by: openapi-operator-gen
