apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "petstore.fullname" . }}-petstore-manager-rolebinding
  labels:
  {{- include "petstore.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "petstore.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "petstore.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
