apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "petstore.fullname" . }}-controller-manager
  labels:
  {{- include "petstore.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "petstore.fullname" . }}-plugin-runner
  labels:
    app.kubernetes.io/component: kubectl-plugin
  {{- include "petstore.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pluginRunner.serviceAccount.annotations | nindent 4 }}
