apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "petstore.fullname" . }}-controller-manager
  labels:
  {{- include "petstore.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
