---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  name: pets.petstore.example.com
spec:
  group: petstore.example.com
  names:
    kind: Pet
    listKind: PetList
    plural: pets
    shortNames:
    - pe
    - pet
    singular: pet
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: State
      type: string
    - jsonPath: .status.externalID
      name: External-ID
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Pet is the Schema for the pets API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: PetSpec defines the desired state of Pet
            type: object
            properties:
              category:
                type: object
              id:
                type: integer
              name:
                type: string
              photoUrls:
                type: array
              status:
                description: pet status in the store
                type: string
                enum:
                - available
                - pending
                - sold
              tags:
                type: array
          status:
            description: PetStatus defines the observed state of Pet
            type: object
            properties:
              state:
                description: Current state of the resource
                type: string
                enum:
                - Pending
                - Syncing
                - Synced
                - Failed
              lastSyncTime:
                description: Last time the resource was synced
                type: string
                format: date-time
              externalID:
                description: ID in the external REST API
                type: string
              message:
                description: Human-readable status message
                type: string
              observedGeneration:
                description: Last observed generation
                type: integer
                format: int64
              conditions:
                description: Conditions
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              response:
                description: Last API response
                type: object
                x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
